# Generated by Django 3.0.2 on 2020-02-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FNDConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fndType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FNDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('algorithm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FNDRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runStartTime', models.DateTimeField()),
                ('runEndTime', models.DateTimeField()),
                ('historyStartTime', models.DateTimeField(null=True)),
                ('historyEndTime', models.DateTimeField(null=True)),
                ('modelFileName', models.CharField(max_length=100)),
                ('tokenizerFileName', models.CharField(max_length=100)),
                ('fndConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newstraining.FNDConfig')),
            ],
        ),
        migrations.CreateModel(
            name='FNDOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableName', models.CharField(max_length=100)),
                ('variableSymbol', models.CharField(max_length=100)),
                ('fndModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newstraining.FNDModel')),
            ],
        ),
        migrations.CreateModel(
            name='FNDModelAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('fndModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newstraining.FNDModel')),
            ],
        ),
        migrations.CreateModel(
            name='FNDInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableName', models.CharField(max_length=100)),
                ('variableSymbol', models.CharField(max_length=100)),
                ('trainingIndicator', models.CharField(max_length=1)),
                ('fndModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newstraining.FNDModel')),
            ],
        ),
        migrations.AddField(
            model_name='fndconfig',
            name='fndModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newstraining.FNDModel'),
        ),
    ]
