# Generated by Django 3.0.2 on 2020-01-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FNDModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("algorithm", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FNDOutput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variableName", models.CharField(max_length=100)),
                ("variableSymbol", models.CharField(max_length=100)),
                (
                    "fndModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newstraining.FNDModel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FNDModelAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                (
                    "fndModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newstraining.FNDModel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FNDInput",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variableName", models.CharField(max_length=100)),
                ("variableSymbol", models.CharField(max_length=100)),
                (
                    "fndModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newstraining.FNDModel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FNDConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fndType", models.CharField(max_length=100)),
                (
                    "fndModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newstraining.FNDModel",
                    ),
                ),
            ],
        ),
    ]
