# Generated by Django 3.0.2 on 2020-01-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newstraining", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="fndconfig", name="fndModel",),
        migrations.AddField(
            model_name="fndmodel",
            name="fndConfig",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="newstraining.FNDConfig",
            ),
            preserve_default=False,
        ),
    ]
