# Generated by Django 3.0.3 on 2020-03-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fndconfig',
            name='fndInput',
            field=models.CharField(max_length=100),
        ),
    ]
