# Generated by Django 3.0.2 on 2020-01-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newstraining", "0002_auto_20200129_1812"),
    ]

    operations = [
        migrations.RemoveField(model_name="fndmodel", name="fndConfig",),
        migrations.AddField(
            model_name="fndconfig",
            name="fndModel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="newstraining.FNDModel",
            ),
            preserve_default=False,
        ),
    ]
