# Generated by Django 3.0.2 on 2020-01-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newstraining", "0003_auto_20200129_2247"),
    ]

    operations = [
        migrations.AddField(
            model_name="fndinput",
            name="trainingIndicator",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
