# Generated by Django 3.0.3 on 2020-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstraining', '0003_auto_20200302_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='fndconfig',
            name='fndOutputs',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
