# Generated by Django 3.0.2 on 2020-02-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newstraining", "0005_fndrundetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fndrundetail",
            name="historyEndTime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="fndrundetail",
            name="historyStartTime",
            field=models.DateTimeField(null=True),
        ),
    ]
