# Generated by Django 3.0.2 on 2020-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newstraining", "0008_auto_20200208_2229"),
    ]

    operations = [
        migrations.RemoveField(model_name="fndrundetail", name="gloveFileLocation",),
    ]
