# Generated by Django 3.0.3 on 2020-03-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=1000, null=True)),
                ('date_posted', models.DateField(null=True)),
                ('fake_status', models.BooleanField(default=False)),
            ],
        ),
    ]
