# Generated by Django 3.0.2 on 2020-01-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsextractor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='date_posted',
        ),
    ]
