# Generated by Django 3.0.2 on 2020-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsextractor", "0002_remove_newsarticle_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="date_posted",
            field=models.DateField(null=True),
        ),
    ]
