# Generated by Django 3.0.2 on 2020-01-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsextractor", "0003_newsarticle_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="fake_status",
            field=models.BooleanField(default=False),
        ),
    ]
